---
title: "Life is Strange"
author: "Michael Puerto"
date: "7/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r getting steam data}

library(tidyverse)
library(zoo)

gamenames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')

```


```{r clean data}
library(lubridate)

LIS <-gamenames %>% filter(str_detect(gamename,pattern = 'Life is Strange')) %>%
  mutate(year_month_day = parse_date(paste0(month, " ", year),"%B %Y"), peak_avg_diff = peak - avg) %>% 
  pivot_longer(cols=c(avg, peak_avg_diff), names_to = 'metric') %>% # 2 new columns, metric and value
  select(gamename, year_month_day, metric,value) %>%
  mutate(gamename = case_when(
  gamename == 'Life is Strange\u0099' ~ 'Life is Strange',
  TRUE ~ as.character(gamename)
))

LIS

```


```{r}
library(psych)
LIS %>% filter(metric == "avg") %>% select(value) %>% min()

```




```{r vis data}
library(pacman)
pacman::p_load(ggstream,showtext,cowplot,extrafont)
library(sysfonts)


background <- '#130A3C'
palette <- c('#1e56a6','#804d2e','#9E2B96')


test<-LIS %>%
  filter(metric =='avg') %>% 
  ggplot(aes(year_month_day , value , fill = gamename)) +
  geom_stream(extra_span = 0, alpha = 0.25) +
  geom_stream(type = "ridge" , bw = 0.75) +
  scale_fill_manual(values = palette) +
  scale_y_continuous(position = "right",breaks = c(0,1000,2000))+
  annotate("text" , x = lubridate::date("2015-03-08"), y = -1000, label = "Source: streamcharts.com\nGraphic: @Mowgl_ii", 
           hjust = 0, size = 3, color = "White" , family = "Ink Free")+
   annotate("text" , x = lubridate::date("2016-07-01"), y = -1150, label = "Average players on Steam", hjust = 0, size = 17, color = "White" , family = "Ink Free") +
  
  # Legends
  
  ## LIS
  
  annotate("linerange" , x = seq(date('2015-10-01'),date("2016-07-01"),'days'), ymin = -800, ymax = -820, size = 3 , color = palette[1]) +

  

  ## LIS BS
  
  annotate("linerange" , x = seq(date('2017-09-01'),date("2018-06-01"),'days'), ymin = -800, ymax = -820, size = 3 , color = palette[3]) +
  
  
  ## LIS 2
  
  annotate("linerange" , x = seq(date("2019-08-01"),date("2020-05-01"), 'days'), ymin = -800, ymax = -820, size = 3 , color = palette[2]) +

  
  theme_void() +
  theme(plot.background = element_rect(fill = background),
        legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(hjust = 0 , face = "bold" , size = 20 , color = "white" , family = "Ink Free"),
        axis.text.y.right = element_text(hjust = 0, vjust = 0.1, face = "bold" , size = 10 , color = "white" , family = "Ink Free"),
        panel.grid = element_blank(),
        plot.margin = margin(2.5,1,1,0, unit = "cm"))

test
```

```{r}
library(magick)
image<-magick::image_read('https://static.wikia.nocookie.net/life-is-strange/images/f/fd/LIS2_Wolves_Transparent.png/revision/latest/scale-to-width-down/1000?cb=20180930181942')
image<-image_negate(image)

```

```{r}
ggdraw(test) +
  draw_image('https://steamuserimages-a.akamaihd.net/ugc/857229700356630685/69EC48062FA0AFD402C93E0D2558ED3BBA6D1D7A/',x = -0.09, y =0.47, height = 0.6,width = 0.6)+
  draw_image('https://www.pikpng.com/pngl/b/213-2136410_life-is-strange-png-butterfly-from-life-is.png',height = 0.13, width = 0.13, x = 0.14,y =0.19)+
  draw_image('https://www.pikpng.com/pngl/b/172-1727425_transparent-skull-png-life-is-strange-chloe-shirt.png',height = 0.15, width = 0.15, x = 0.41,y = 0.19)+
  draw_image(image,height = 0.22, width = 0.22, x = 0.63,y = 0.13)
ggsave('lisplot.png', dpi = 320,height = 10,width = 16)
```


